
import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import "swiper/css/bundle";
import "./globals.scss";

// Google Fonts import
import { Funnel_Display, Kanit, Space_Grotesk, Teko, DM_Sans, Inter, Playfair_Display, Poppins, Sora, Plus_Jakarta_Sans, Familjen_Grotesk, Phudu } from "next/font/google";

const funnelDisplay = Funnel_Display({
  weight: ["300", "400", "500", "600", "700", "800"], // original URL 300..800
  subsets: ["latin"],
  variable: "--font-funnel-display",
});

const kanit = Kanit({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-kanit",
});

const spaceGrotesk = Space_Grotesk({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-space-grotesk",
});

const teko = Teko({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-teko",
});

const dmSans = DM_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900", "1000"],
  style: ["normal", "italic"], // original URL e italic ache
  subsets: ["latin"],
  variable: "--font-dm-sans",
});

const inter = Inter({
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-inter",
});

const playfairDisplay = Playfair_Display({
  weight: ["400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-playfair-display",
});

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

const sora = Sora({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-sora",
});

const plusJakartaSans = Plus_Jakarta_Sans({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-plus-jakarta-sans",
});

const familjenGrotesk = Familjen_Grotesk({
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-familjen-grotesk",
});

const phudu = Phudu({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-phudu",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${funnelDisplay.variable} 
          ${kanit.variable} 
          ${spaceGrotesk.variable} 
          ${teko.variable} 
          ${dmSans.variable} 
          ${inter.variable} 
          ${playfairDisplay.variable} 
          ${poppins.variable} 
          ${sora.variable} 
          ${plusJakartaSans.variable} 
          ${familjenGrotesk.variable} 
          ${phudu.variable}
        `}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}