// Create a central animation configuration object
// Each key represents a route (page path)
// Each value is an array of animation functions to run on that route

import { animateImageBorderRadiusOnScroll, applyFadeInAnimation, applyWebGLHoverEffect, buttonHoverAnimation, buttonMoveAnimation, initAwardsThumbsAnimation, initBounceOnAnim, initButtonHoverAnimation, initFixedTitleAnimation, initFunfactAnimation, initPanelPinScrollAnimation, initPerspectiveSlider, initPinnedServiceScrollPanels, initPortfolioAnimation, initPortfolioItemAnimation, initPortfolioPanelAnim, initPortfolioPerspective, initPortfolioPinAnim, initPortfolioTextAnimation, initRevealOnHover, initRotateTextAnim, initScaleImageHoverAnim, initScrollImageAnim, initScrollMovingText, initScrollRotateImages, initScrollScaleImages, initScrollTextInvert, initSectionImageSlicer, initSectionSliceRevealAnim, initServiceImageSlider, initServiceVpAnimation, initShowcaseSnapSlider, initSkillPanelAnim, initTextAnim, initTextPerspectiveAnim, initTextRevealAnim, initTextScaleAnimationFromBottom, initVideoImgAnim, initWebglHover, splitTextAnimation, textScaleAnimBottom, titleMiddleAnimetion } from "@/hooks";

export const animationConfig: Record<string, (() => void)[]> = {
    //Light page animation
    "/it-consulting": [titleMiddleAnimetion, animateImageBorderRadiusOnScroll, initPanelPinScrollAnimation, applyWebGLHoverEffect],
    "/seo-agency": [initTextRevealAnim],
    "/photographer": [initScrollTextInvert, initRevealOnHover],
    "/digital-agency": [buttonHoverAnimation, buttonMoveAnimation, initBounceOnAnim, initWebglHover, initRotateTextAnim, initTextPerspectiveAnim, initScrollTextInvert],
    "/ai-startup": [initWebglHover, initScaleImageHoverAnim, initSectionSliceRevealAnim, initShowcaseSnapSlider, textScaleAnimBottom, initTextAnim],
    "/video-production": [textScaleAnimBottom, initVideoImgAnim, initAwardsThumbsAnimation, initScrollTextInvert, initRevealOnHover, initServiceVpAnimation, initPortfolioPerspective, initWebglHover, initTextScaleAnimationFromBottom],
    "/business-consulting": [initScrollTextInvert],
    "/it-solution": [splitTextAnimation, initScrollRotateImages, initScrollMovingText, initTextRevealAnim, initScrollScaleImages, applyWebGLHoverEffect],
    "/personal-portfolio": [initPanelPinScrollAnimation, buttonHoverAnimation, initScrollTextInvert, initPinnedServiceScrollPanels, initBounceOnAnim, applyWebGLHoverEffect, splitTextAnimation, initRotateTextAnim],
    "/web-design-agency": [buttonHoverAnimation, initServiceImageSlider, initSectionImageSlicer, initPortfolioPanelAnim, initRevealOnHover, initTextPerspectiveAnim],
    "/construction": [initScrollImageAnim, initPortfolioPinAnim],
    "/ingenierie": [initRotateTextAnim],
    "/filiales": [initRevealOnHover, initPortfolioPinAnim],
    "/references": [buttonHoverAnimation, initRotateTextAnim],
    "/vision": [buttonHoverAnimation, buttonMoveAnimation, initBounceOnAnim, initRotateTextAnim, initScrollTextInvert],
    "/ai-agency": [applyWebGLHoverEffect],
    "/plumbing-service": [initServiceImageSlider, initScrollMovingText, initSkillPanelAnim, initSectionSliceRevealAnim, applyFadeInAnimation, initScrollTextInvert],
    "/creative-agency": [buttonHoverAnimation, initPortfolioAnimation, initSectionImageSlicer, initRevealOnHover, applyWebGLHoverEffect, initButtonHoverAnimation, initRotateTextAnim, initTextPerspectiveAnim],
    "/medical": [applyFadeInAnimation, initFunfactAnimation, initWebglHover, textScaleAnimBottom, initTextRevealAnim],
    "/startup-agency": [buttonHoverAnimation, initScrollTextInvert, initPortfolioItemAnimation, initPortfolioTextAnimation, initWebglHover, initSectionImageSlicer, initFixedTitleAnimation, initRotateTextAnim],
    "/portfolio-col-3": [buttonHoverAnimation, initRotateTextAnim],
    "/portfolio-col-4": [buttonHoverAnimation, initRotateTextAnim],
    "/portfolio-masonry": [buttonHoverAnimation, buttonMoveAnimation, initRotateTextAnim],
    "/portfolio-showcase-full":[initPortfolioPanelAnim],
    "/portfolio-col-2": [initPortfolioItemAnimation, initRotateTextAnim],
    "/blog-grid": [applyWebGLHoverEffect, initRotateTextAnim],
    "/blog-grid-2": [applyWebGLHoverEffect, initRotateTextAnim],
    "/blog-standard": [initRotateTextAnim],
    "/blog-details": [initRotateTextAnim],
    "/blog-details-2": [initRotateTextAnim],
    "/about-me": [initRotateTextAnim, initBounceOnAnim, initScrollTextInvert, initPinnedServiceScrollPanels],
    "/about-creative": [buttonHoverAnimation, buttonMoveAnimation, initBounceOnAnim, initRotateTextAnim, initScrollTextInvert],
    "/about-modern": [initScrollTextInvert],
    "/team": [initRevealOnHover, initPortfolioPinAnim],
    "/team-details": [applyWebGLHoverEffect, initRotateTextAnim, buttonHoverAnimation, buttonMoveAnimation],
    "/faq": [initRotateTextAnim, buttonHoverAnimation, buttonMoveAnimation],
    "/faq-2": [initRotateTextAnim, buttonHoverAnimation, buttonMoveAnimation],
    "/pricing": [initRotateTextAnim, buttonHoverAnimation, buttonMoveAnimation],
    "/shop": [buttonHoverAnimation, buttonMoveAnimation],
    "/service-1": [initRotateTextAnim],
    "/service-4": [initRotateTextAnim],
    "/service-2": [initScrollTextInvert,initRotateTextAnim],
    "/service-3": [initScrollTextInvert, initPinnedServiceScrollPanels,initRotateTextAnim],
    "/service-details": [initRotateTextAnim],
    "/service-details-2": [initTextAnim, initTextRevealAnim, initRotateTextAnim],
    "/awards": [initAwardsThumbsAnimation],
    "/error": [initRotateTextAnim, buttonHoverAnimation, buttonMoveAnimation],
    "/contact": [initRotateTextAnim, buttonHoverAnimation, buttonMoveAnimation],
    "/contact-us": [initRotateTextAnim, buttonHoverAnimation, buttonMoveAnimation],
    "/portfolio-details-gallery": [initRotateTextAnim],
    "/portfolio-details": [initRotateTextAnim],
    "/portfolio-perspective-slider": [initPerspectiveSlider],

    //Dark page animation
    "/dark/it-consulting": [titleMiddleAnimetion, animateImageBorderRadiusOnScroll, initPanelPinScrollAnimation, applyWebGLHoverEffect],
    "/dark/seo-agency": [initTextRevealAnim],
    "/dark/photographer": [initScrollTextInvert, initRevealOnHover],
    "/dark/digital-agency": [buttonHoverAnimation, buttonMoveAnimation, initBounceOnAnim, initWebglHover, initRotateTextAnim, initTextPerspectiveAnim, initScrollTextInvert],
    "/dark/ai-startup": [initWebglHover, initScaleImageHoverAnim, initSectionSliceRevealAnim, initShowcaseSnapSlider, textScaleAnimBottom, initTextAnim],
    "/dark/video-production": [textScaleAnimBottom, initVideoImgAnim, initAwardsThumbsAnimation, initScrollTextInvert, initRevealOnHover, initServiceVpAnimation, initPortfolioPerspective, initWebglHover, initTextScaleAnimationFromBottom],
    "/dark/business-consulting": [initScrollTextInvert],
    "/dark/it-solution": [splitTextAnimation, initScrollRotateImages, initScrollMovingText, initTextRevealAnim, initScrollScaleImages, applyWebGLHoverEffect],
    "/dark/personal-portfolio": [initPanelPinScrollAnimation, buttonHoverAnimation, initScrollTextInvert, initPinnedServiceScrollPanels, initBounceOnAnim, applyWebGLHoverEffect, splitTextAnimation, initRotateTextAnim],
    "/dark/web-design-agency": [buttonHoverAnimation, initServiceImageSlider, initSectionImageSlicer, initPortfolioPanelAnim, initRevealOnHover, initTextPerspectiveAnim],
    "/dark/construction": [initScrollImageAnim, initPortfolioPinAnim],
    "/dark/ai-agency": [applyWebGLHoverEffect],
    "/dark/plumbing-service": [initServiceImageSlider, initScrollMovingText, initSkillPanelAnim, initSectionSliceRevealAnim, applyFadeInAnimation, initScrollTextInvert],
    "/dark/creative-agency": [buttonHoverAnimation, initPortfolioAnimation, initSectionImageSlicer, initRevealOnHover, applyWebGLHoverEffect, initButtonHoverAnimation, initRotateTextAnim, initTextPerspectiveAnim],
    "/dark/medical": [applyFadeInAnimation, initFunfactAnimation, initWebglHover, textScaleAnimBottom, textScaleAnimBottom, initTextRevealAnim],
    "/dark/startup-agency": [buttonHoverAnimation, initScrollTextInvert, initPortfolioItemAnimation, initPortfolioTextAnimation, initWebglHover, initSectionImageSlicer, initFixedTitleAnimation, initRotateTextAnim],
    "/dark/portfolio-col-3": [buttonHoverAnimation, initRotateTextAnim],
    "/dark/portfolio-col-4": [buttonHoverAnimation, initRotateTextAnim],
    "/dark/portfolio-masonry": [buttonHoverAnimation, buttonMoveAnimation, initRotateTextAnim],
    "/dark/portfolio-showcase-full":[initPortfolioPanelAnim],
    "/dark/portfolio-col-2": [initPortfolioItemAnimation, initRotateTextAnim],
    "/dark/blog-grid": [applyWebGLHoverEffect, initRotateTextAnim],
    "/dark/blog-grid-2": [applyWebGLHoverEffect, initRotateTextAnim],
    "/dark/blog-standard": [initRotateTextAnim],
    "/dark/blog-details": [initRotateTextAnim],
    "/dark/blog-details-2": [initRotateTextAnim],
    "/dark/about-me": [initRotateTextAnim, initBounceOnAnim, initScrollTextInvert, initPinnedServiceScrollPanels],
    "/dark/about-creative": [buttonHoverAnimation, buttonMoveAnimation, initBounceOnAnim, initRotateTextAnim, initScrollTextInvert],
    "/dark/about-modern": [initScrollTextInvert],
    "/dark/team": [initRevealOnHover, initPortfolioPinAnim],
    "/dark/team-details": [applyWebGLHoverEffect, initRotateTextAnim, buttonHoverAnimation, buttonMoveAnimation],
    "/dark/faq": [initRotateTextAnim, buttonHoverAnimation, buttonMoveAnimation],
    "/dark/faq-2": [initRotateTextAnim, buttonHoverAnimation, buttonMoveAnimation],
    "/dark/pricing": [initRotateTextAnim, buttonHoverAnimation, buttonMoveAnimation],
    "/dark/shop": [buttonHoverAnimation, buttonMoveAnimation],
    "/dark/service-1": [initRotateTextAnim],
    "/dark/service-4": [initRotateTextAnim],
    "/dark/service-2": [initScrollTextInvert,initRotateTextAnim],
    "/dark/service-3": [initScrollTextInvert, initPinnedServiceScrollPanels,initRotateTextAnim],
    "/dark/service-details": [initRotateTextAnim],
    "/dark/service-details-2": [initTextAnim, initTextRevealAnim, initRotateTextAnim],
    "/dark/awards": [initAwardsThumbsAnimation],
    "/dark/error": [initRotateTextAnim, buttonHoverAnimation, buttonMoveAnimation],
    "/dark/contact": [initRotateTextAnim, buttonHoverAnimation, buttonMoveAnimation],
    "/dark/contact-us": [initRotateTextAnim, buttonHoverAnimation, buttonMoveAnimation],
    "/dark/portfolio-details-gallery": [initRotateTextAnim],
    "/dark/portfolio-details": [initRotateTextAnim],
    "/dark/portfolio-perspective-slider": [initPerspectiveSlider],

};
